// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect.Clase;

namespace Proiect.Migrations
{
    [DbContext(typeof(ClientRezervareContext))]
    [Migration("20210601192514_Initiala")]
    partial class Initiala
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14");

            modelBuilder.Entity("Proiect.Clase.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cnp")
                        .HasColumnType("TEXT");

                    b.Property<int>("NrPersoane")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nume")
                        .HasColumnType("TEXT");

                    b.Property<int>("Telefon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Varsta")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Clienti");
                });
#pragma warning restore 612, 618
        }
    }
}
